---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: {{ cookiecutter.scenario_name }}
lint:
  name: yamllint
platforms:
  - name: {{ cookiecutter.role_name }}-{{ cookiecutter.scenario_name }}-centos
    image: centos:7
    # command: /sbin/init
    # privileged: true
  - name: {{ cookiecutter.role_name }}-{{ cookiecutter.scenario_name }}-ubuntu-bionic
    image: ubuntu:bionic
    # command: /lib/systemd/systemd
    # privileged: true
  - name: {{ cookiecutter.role_name }}-{{ cookiecutter.scenario_name }}-debian-10
    image: debian:10
    # command: /lib/systemd/systemd
    # privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
