---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: centos
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: {{ cookiecutter.role_name }}-centos8
    image: centos:8
    # command: /sbin/init
    # privileged: true
    dockerfile: ../resources/playbooks/Dockerfile.j2
  - name: {{ cookiecutter.role_name }}-centos7
    image: centos:7
    # command: /sbin/init
    # privileged: true
    dockerfile: ../resources/playbooks/Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
  log: true
  options:
    vvv: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
      verbosity: 3
verifier:
  name: testinfra
  directory: ../resources/tests/
