---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: centos
lint: |
  yamllint .
  ansible-lint molecule/centos/*.yml
  flake8
platforms:
  - name: {{ cookiecutter.role_name }}-centos
    image: centos:7
    # command: /sbin/init
    # privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
verifier:
  name: testinfra
